language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: Oz0jn9zQ7JFeqAdMvigMq+I3e34i80MJ3IzPX9oPUct5rG+VIbh5xcVskx9yOlWRsfheuMEJs4adWYG6PctZrkEMq5seiC8i0XA11aPeGR2gOj6yIWCWwf8Rw/pIU+vcKalovL3fCthFZVJOY/YhwqgnC54qKzE8dG9a4rQKDY36JzLTCO2wDj/0M+MNLqUAeOBjvLVbFD+CfzpLfuwQYvXLFL5t28rgvnzbAfm5EVOdhSlpL0pvLVWNXNtG2+IF1UvKkmq3wnIxPZWgPt9JXU/xDgXZi+YTdvAXuafoWWDqKSyeV3dN4razSyPDMdI+GJxTSjNfANQvGK2tznS6mtdCa4XyWdDfi2SvtW6fpmMrKzYxhnxDNIgILavL2/cIy4ck7MWxf5SmsrVTfkEvZY7+UWymMp3AHQRTpV0BR4gJmmjYlx4POFLtuw4EFLucV0VQg0LRJnwjuXO1UEdQKI6ItgFkWwa2Pf9wqywAtHxJD4BkRePl9tO0Bc/DmN+hSaLgPivTrIZFcpRE1+wjnp+MXF8CfIALMmExNJlh5IW6dq3goI78TTbQSZOspwwwvqVmAtSy/K66aqklrQtsln5+d25ganmGTePjgHePSSMOYb9Kf832ENNF1u5kpWcSQ2vpfEpG67rUv/Pi1JWdQgLdn4RilkZYwHeO863e5js=
  on:
    tags: true
    repo: noflo/noflo-mclighting
